//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Calculations')
export class CalculationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  operationPerformed: number;

  @Column('real', { nullable: true })
  result: number;

  @Column('integer', { nullable: true })
  user: number;
}
