//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Users: [
      {
        username: 'username 1',
        email: 'email 1',
        password: 'password 1',
        id: 66,
      },
      {
        username: 'username 2',
        email: 'email 2',
        password: 'password 2',
        id: 44,
      },
      {
        username: 'username 3',
        email: 'email 3',
        password: 'password 3',
        id: 78,
      },
      {
        username: 'username 4',
        email: 'email 4',
        password: 'password 4',
        id: 38,
      },
      {
        username: 'username 5',
        email: 'email 5',
        password: 'password 5',
        id: 85,
      },
    ],
    Calculations: [
      { operationPerformed: 1, result: 0.84, user: 1, id: 34 },
      { operationPerformed: 2, result: 0.79, user: 2, id: 93 },
      { operationPerformed: 3, result: 0.94, user: 3, id: 87 },
      { operationPerformed: 4, result: 0.09, user: 4, id: 94 },
      { operationPerformed: 5, result: 0.03, user: 5, id: 67 },
    ],
    Operations: [
      {
        operationName: 'operationName 1',
        symbolicRepresentation: 'symbolicRepresentation 1',
        id: 31,
      },
      {
        operationName: 'operationName 2',
        symbolicRepresentation: 'symbolicRepresentation 2',
        id: 55,
      },
      {
        operationName: 'operationName 3',
        symbolicRepresentation: 'symbolicRepresentation 3',
        id: 12,
      },
      {
        operationName: 'operationName 4',
        symbolicRepresentation: 'symbolicRepresentation 4',
        id: 3,
      },
      {
        operationName: 'operationName 5',
        symbolicRepresentation: 'symbolicRepresentation 5',
        id: 20,
      },
    ],
  },
};
export default data;
