//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Users: {
      name: 'Users',
      fields: {
        username: 'Username',
        email: 'Email',
        password: 'Password',
        id: 'id',
      },
    },
    Calculations: {
      name: 'Calculations',
      fields: {
        operationPerformed: 'Operation Performed',
        result: 'Result',
        user: 'User',
        id: 'id',
      },
    },
    Operations: {
      name: 'Operations',
      fields: {
        operationName: 'Operation Name',
        symbolicRepresentation: 'Symbolic Representation',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Users: {
      name: 'Users (fr)',
      fields: {
        username: 'Username (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        id: 'id',
      },
    },
    Calculations: {
      name: 'Calculations (fr)',
      fields: {
        operationPerformed: 'Operation Performed (fr)',
        result: 'Result (fr)',
        user: 'User (fr)',
        id: 'id',
      },
    },
    Operations: {
      name: 'Operations (fr)',
      fields: {
        operationName: 'Operation Name (fr)',
        symbolicRepresentation: 'Symbolic Representation (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
